name: kosartur_unsupervised_rdpad_seg50_clust15_200rdpad
dataset_root: DATASET1/kosartur_unsupervised_rdpad_seg50_clust15_200rdpad
dataset_type: single
images_root: images
list: lists/images.txt
gt_dir: labels
pred_dir: ""
n_classes: 15
features_dir: ""
preprocessed_dir: ""
derained_dir: ""
eigenseg_dir: ""
