name: hamzaoran_unsup_gaussian_seg50_clust15_clusters
seg_for_eval: ['segmaps']
method: grid
count: 1
simple: True
sweep_id: null
config:
    segments_num: [50]
    clusters_num: [15]

    crf:
        num_classes: [15]
        w1: [15]
        alpha: [7]
        beta: [10]
        w2: [5]
        gamma: [5]
        it: [10]
